### PR TITLE
Added new animation

### PR DESCRIPTION
**Pull request by AnshumanFauzdar**
https://user-images.githubusercontent.com/40523329/135588955-4d5cb711-ebd4-4bd1-8dc7-3af4ab1f21d1.mp4

Here is a demo for the animation.
I have removed minified js and css as jsdelivr provides minified versions automatically.

### CODE REVIEW

**Comment by cachecleanerjeet** [comment]
I think this animation is taking much more place 🤔
That round blinking animation should be removed!

**Comment by AnshumanFauzdar** [comment]
Any other suggestion for animation?

**Comment by cachecleanerjeet** [comment]
No suggestion for animation, But I think we have to make the contact request on the full page on mobile. Because you open that form on mobile (with the keyboard open), Some of the fields are hidden automatically!

**Comment by cachecleanerjeet** [comment]
Thanks for your PR BTW!

**Comment by cachecleanerjeet** [comment]
This is okay in IOS though! But android is buggy.
ios
android

**Comment by AnshumanFauzdar** [comment]
Ohh it's should be fixed before animation :)

**Comment by AnshumanFauzdar** [comment]
Let me work on this again, will try to implement more subtle animation.

**Comment by cachecleanerjeet** [comment]
Sounds good!

Thank you ☺

**Comment by AnshumanFauzdar** [comment]
Hey @cachecleanerjeet one more question.
How do you test server less workers on local machine or what is your workflow for testing?

**Comment by cachecleanerjeet** [comment]
You mean unit testing? Or the development environment while writing the code?

**Comment by AnshumanFauzdar** [comment]
> You mean unit testing? Or the development environment while writing the code?

Both :)

**Comment by AnshumanFauzdar** [comment]
Sounds very technical, will try tho!
Thanks!

**Pull request closed without merging**
